### DISCUSSION TITLE
Cargo build error: required because of the requirements on the impl of `Pattern<'a>` for `regex::Regex`

### DISCUSSION THREAD

**Discussion by nicolaslazo** [rust-lang/regex#834] [Q&A] [answered]
Hi! Could I ask for some help with my first Rust project?

Basically I'm trying to split a string on a regex keeping the separators with `str::match_indices`. I made sure to use nightly Rust and I _think_ I enabled the "pattern" feature properly.

**src/main.rs**
```rust
struct RegexInclusiveSplit<'a> {
    text: &'a str,
    indices_iter: &'a str::MatchIndices<'a, Regex>,
    last_item_consumed: (usize, &'a str),  // Consumed from indices_iter
    next_token_index: usize,
}

/* Some more code... 
impl RegexInclusiveSplit<'_> {
    fn new(&mut self, text: &str, pattern: Regex) -> Self {
       ...

impl<'a> Iterator for RegexInclusiveSplit<'a> {
    type Item = &'a str;

    fn next(&mut self) -> Option<Self::Item> {
       ...
*/

fn main() {
    let input_text = fs::read_to_string("neuromancer.txt").unwrap();
    let token_delimiter_re = Regex::new(r"(([\.,:]?( |\t|\n)+)|--)").unwrap();

    for token in RegexInclusiveSplit::new(input_text, token_delimiter_re) {
        println!("{}", token);
    }
}
```

**rust-toolchain.toml**
```toml
[toolchain]
channel = "nightly"
```

**Cargo.toml**
```toml
[package]
name = "rust-markov-strings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.regex]
version = "*"
features = ["std", "pattern"]

[features]
default = ["regex/pattern"]
```

However, I get the following compilation error:
```
error[E0277]: expected a `FnMut<(char,)>` closure, found `regex::Regex`
    --> src/main.rs:6:23
     |
6    |     indices_iter: &'a str::MatchIndices<'a, Regex>,
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an `FnMut<(char,)>` closure, found `regex::Regex`
     |
     = help: the trait `FnMut<(char,)>` is not implemented for `regex::Regex`
     = note: required because of the requirements on the impl of `Pattern<'a>` for `regex::Regex`
```

So I'm guessing I did something wrong in my `Cargo.toml`? Those `[dependencies.regex]` and `[features]` feel redundant.

I'd appreciate any feedback you can provide!
